files:
  include: 'scss/**/*.scss'
  ignore:
    - 'scss/vendors/**/*.*'

options:
  formatter: stylish # Console Log
  merge-default-rules: false # Disable Defaults

rules:
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - allow-single-line: true
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 2
    - leading-underscore: false
    - filename-extension: false
  empty-args:
    - 2
  empty-line-between-blocks:
    - 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  nesting-depth:
    - 2
    - max-depth: 4
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 2
    - extra-properties:
      - overflow-scrolling
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-trailing-whitespace: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-universal-selectors: 2
  no-vendor-prefixes:
    - 2
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 1
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  property-sort-order:
    - 0
  property-units:
    - 0
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  space-around-operator: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 2
